### ISSUE TITLE
NPE while trying to encode the video (after migration to gradle)

### ISSUE THREAD

**Issue by kontownik** [netguru/qa-selenium-java-framework#34]
After we migrated to Gradle, encoding the raw .avi files is failing. Also, I was unable to open the .avi files, so it could be broken.

stacktrace:
(in progress)

logs:
```
sie 18, 2019 2:19:24 PM ws.schild.jave.DefaultFFMPEGLocator copyFile
SEVERE: Could not find ffmpeg executable for native/ffmpeg-x86_64-osx is the correct platform jar included?
```

**Comment by agamamla** [comment]
`java.lang.NullPointerException
        at java.base/java.util.Objects.requireNonNull(Objects.java:221)
        at java.base/java.nio.file.Files.copy(Files.java:3034)
        at ws.schild.jave.DefaultFFMPEGLocator.copy(DefaultFFMPEGLocator.java:167)
        at ws.schild.jave.DefaultFFMPEGLocator.copyFile(DefaultFFMPEGLocator.java:132)
        at ws.schild.jave.DefaultFFMPEGLocator.<init>(DefaultFFMPEGLocator.java:92)
        at ws.schild.jave.MultimediaObject.<init>(MultimediaObject.java:60)
        at utilities.FailureHandler.encodeVideoToFlv(FailureHandler.java:157)
        at utilities.FailureHandler.stopVideoRecord(FailureHandler.java:140)
        at steps.Hooks.ceaseTestCase(Hooks.java:31)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at cucumber.runtime.Utils$1.call(Utils.java:40)
        at cucumber.runtime.Timeout.timeout(Timeout.java:16)
        at cucumber.runtime.Utils.invoke(Utils.java:34)
        at cucumber.runtime.java.JavaHookDefinition.execute(JavaHookDefinition.java:60)
        at cucumber.runtime.Runtime.runHookIfTagsMatch(Runtime.java:224)
        at cucumber.runtime.Runtime.runHooks(Runtime.java:212)
        at cucumber.runtime.Runtime.runAfterHooks(Runtime.java:206)
        at cucumber.runtime.model.CucumberScenario.run(CucumberScenario.java:46)
        at cucumber.runtime.model.CucumberFeature.run(CucumberFeature.java:165)
        at cucumber.runtime.Runtime.run(Runtime.java:122)
        at cucumber.api.cli.Main.run(Main.java:36)
        at cucumber.api.cli.Main.main(Main.java:18)
`
